<<<<<<< HEAD
name: Buidl & Test .NET Core
=======
name: .NET Core Build & Test
>>>>>>> 922b61bc18893fbf73e8eb7828ea6db9c3359905

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Mi primer job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    # - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build '.\back\Services\Catalog\Catalog.API\Catalog.API.csproj'
